package protocol;

public enum ErrorCode {
    INVALID_MESSAGE,
    INVALID_JSON,
    INVALID_DIRECTION,
    UNKNOWN_PLAYER,
    GAME_NOT_STARTED,
    GAME_ALREADY_STARTED,
    GAME_FINISHED,
    UNSUPPORTED_PROTOCOL_VERSION
}
